name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
        working-directory: ./subdirectory
        
      - name: Run tests
        run: yarn test
